global:
  scrape_interval: 5m
  scrape_timeout: 1m
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'springboot-monitoring'
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets:
      - 'docker.for.mac.host.internal:8080'
    tls_config:
      insecure_skip_verify: true